### ISSUE TITLE
Version 4.0.3 not compatible with other AWS libraries ( Ex: version 1.11.904 )

### ISSUE THREAD

**Issue by Ostico** [aws/aws-sigv4-auth-cassandra-java-driver-plugin#20]
This version requires 
```
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-core</artifactId>
            <version>1.11.717</version>
        </dependency>
```
which is incompatible with newest com.amazonaws library releases 

```
java.lang.NoSuchFieldError: ENDPOINT_OVERRIDDEN
	at com.amazonaws.services.sqs.AmazonSQSClient.executeGetQueueUrl(AmazonSQSClient.java:1200) ~[aws-java-sdk-sqs-1.11.904.jar:?]
	at com.amazonaws.services.sqs.AmazonSQSClient.getQueueUrl(AmazonSQSClient.java:1182) ~[aws-java-sdk-sqs-1.11.904.jar:?]
	at com.amazon.sqs.javamessaging.AmazonSQSMessagingClientWrapper.queueExists(AmazonSQSMessagingClientWrapper.java:220) ~[amazon-sqs-java-messaging-lib-1.0.8.jar:?]
```

**Comment by bhouse99** [comment]
The latest release (4.0.4) should be compatible with aws sdk 2, so hopefully this issue is now resolved.

**Comment by Ostico** [comment]
Thank you!
